# Generated by Django 3.0.3 on 2020-02-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusDriver', '0002_bus_departuretime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='SeatsNumber',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='bus',
            name='isFull',
            field=models.BooleanField(blank=True, default=False, editable=False, null=True),
        ),
    ]
