# Generated by Django 3.0.3 on 2020-02-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusDriver', '0003_auto_20200217_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='PreservedSeats',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='bus',
            name='SeatsNumber',
            field=models.IntegerField(),
        ),
    ]
