# Generated by Django 3.0.3 on 2020-02-17 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BusDriver', '0004_auto_20200217_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='bus',
        ),
        migrations.AddField(
            model_name='bus',
            name='drivername',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BusDriver.Driver'),
        ),
    ]
