# Generated by Django 3.0.3 on 2020-02-17 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BusDriver', '0005_auto_20200217_1140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='_to',
            new_name='destnation',
        ),
    ]
