# Generated by Django 3.0.3 on 2020-02-17 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BusDriver', '0006_auto_20200217_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='_from',
            new_name='origin',
        ),
    ]
