# Generated by Django 3.0.3 on 2020-02-17 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BusDriver', '0007_auto_20200217_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='destnation',
            new_name='destination',
        ),
    ]
